---
version: '2'
services:
  common:
    build: "."
    environment:
      DATABASE_URL: postgres://postgres:FVCwU-8PGKwNIMAsZJKY_Q@db:5432/postgres
  app:
    extends:
      service: common
    command: martini-example
    links:
    - db
    build: "."
    ports:
    - 3000:3000
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: FVCwU-8PGKwNIMAsZJKY_Q
